export const APP_STRINGS = {
  navigation: {
    home: "Home",
    search: "Search",
    appointments: "Appointments",
    favorites: "Favorites",
    profile: "Profile",
  },
  auth: {
    signIn: "Sign In",
    signInTitle: "Sign in to continue",
    signInSubtitle: "Book appointments easily and manage your reservations",
    signUp: "Sign up",
    signUpTitle: "Create your account",
    signUpSubtitle: "Join us to book and manage your appointments",
    continueWithFacebook: "Continue with Facebook",
    continueWithGoogle: "Continue with Google",
    continueWithPhone: "Use phone number",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    createAccount: "Create account",
    close: "Close",
    signOut: "Sign out",
    phoneNumber: {
      title: "Enter your phone number",
      label: "Mobile phone",
      placeholder: "Enter your phone number",
      continue: "Continue",
      searchPlaceholder: "Search country or code",
    },
    verification: {
      title: "Enter 6-digit code",
      subtitle: "Code was sent via SMS to",
      placeholder: "Enter code",
      verify: "Verify code",
      resend: "Didn't receive a code?",
      timer: "Code expires in",
      seconds: "seconds",
    },
    continueWithApple: "Continue with Apple",
  },
  profile: {
    accountDetails: "Account Details",
    notifications: "Notifications",
    notificationSettings: "Notification Settings",
    memberships: "Memberships",
    support: "Support Center",
    appointments: "Appointments",
  },
  search: {
    placeholder: "Search services, providers...",
    selectCity: "Select city",
    filters: "Filters",
    title: "Search",
    searchPlaceholder: "Search for service or provider",
    yourLocation: "Your location",
    categories: {
      hairStyling: "Hair styling",
      barberShop: "Barber shop",
      nails: "Nails",
      cosmetics: "Cosmetics",
      lashes: "Lash extensions",
      permanentHairRemoval: "Permanent hair removal",
      bodyTreatments: "Body treatments",
      medicalAesthetics: "Medical aesthetics",
      massage: "Massage",
      micropigmentation: "Micropigmentation",
      makeup: "Makeup",
    },
    promoted: "PROMOTED",
    reviews: "reviews",
    inCity: "in",
  },
  appointments: {
    upcoming: "Upcoming",
    past: "Past",
    completed: "Completed",
    noShow: "No-show",
  },
  common: {
    loading: "Loading...",
    error: "Something went wrong",
    empty: "No results found",
  },
  filters: {
    title: "Filters",
    allResults: "All results",
    discounts: "Discounts",
  },
  home: {
    searchPlaceholder: "Search service, salon",
    selectCity: "București",
    bookOnline: "Book online",
    appointments: {
      completed: "COMPLETED",
      upcoming: "UPCOMING",
      viewAll: "View all appointments",
    },
  },
  provider: {
    services: "SERVICII",
    specialists: "SPECIALIȘTI",
    reviews: "RECENZII",
    contact: "CONTACT",
    chooseSpecialist: "Alege specialist",
    schedule: "Programează",
    reviewsAndRatings: "Recenzii și evaluări",
    addReview: "Adaugă recenzie",
    seeMoreReviews: "Vezi mai multe recenzii",
    giftCard: {
      title: "Cumpără Card Cadou",
      subtitle: "Valabil 6 luni la",
      seeDetails: "Vezi detalii",
    },
    workingHours: "Program de lucru",
    seeDirections: "Vezi direcții de navigare",
    searchService: "Caută serviciu",
    days: {
      monday: "Luni",
      tuesday: "Marți",
      wednesday: "Miercuri",
      thursday: "Joi",
      friday: "Vineri",
      saturday: "Sâmbătă",
      sunday: "Duminică",
    },
    status: {
      open: "Deschis",
      closed: "Închis",
      opensAt: "Deschide Sâmbătă la",
    },
  },
} as const

